name: Copy folder to other branch

on:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'dist'
          TARGET_BRANCH: 'use-components'
        run: |
          npm install
          npm run build
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add $files
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch